// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"blog-server/cmd"
	"blog-server/internal/repo"
	"blog-server/internal/routes"
	"blog-server/internal/service"
)

// Injectors from wire.go:

func InitApis() *cmd.ApiRoutes {
	iEssayRepo := repo.NewEssayRepo()
	iTagRepo := repo.NewTagRepo()
	iEssayService := service.NewEssayService(iEssayRepo, iTagRepo)
	iEssayRouter := routes.NewEssayRouter(iEssayService)
	apiRoutes := cmd.NewApiRoutes(iEssayRouter)
	return apiRoutes
}
